"""Country-specific local RSS feeds used by the on-demand country report.

Merged with the global RSS_FEEDS list from geoint_agent.py at query time so
the LLM sees both wire-service coverage and one or two locally-anchored
outlets for the target country.

Keys are lower-case ISO-3166 alpha-3 codes (to match the frontend country
database), and the values are lists of (source_name, url, bias) tuples.
Bias uses the same 5-step scale as the global agent.
"""

COUNTRY_FEEDS = {
    # -------- Africa --------
    "dza": [("El Watan (English)", "https://www.aps.dz/en/feed/rss2.xml", "lean_left")],
    "egy": [("Egypt Independent", "https://egyptindependent.com/feed/", "center")],
    "eth": [("Addis Standard", "https://addisstandard.com/feed/", "center")],
    "ken": [("Daily Nation KE", "https://nation.africa/kenya/rss", "center")],
    "nga": [("Punch Nigeria", "https://punchng.com/feed/", "center")],
    "zaf": [("News24 Top Stories", "https://feeds.news24.com/articles/news24/TopStories/rss", "center")],
    "mar": [("Morocco World News", "https://www.moroccoworldnews.com/feed", "center")],
    "tun": [("Tunisia Live", "https://tunisialive.net/feed/", "center")],
    "sdn": [("Sudan Tribune", "https://sudantribune.com/feed/", "center")],
    "ssd": [("Sudan Tribune", "https://sudantribune.com/feed/", "center")],
    "gha": [("Ghana Web", "https://www.ghanaweb.com/GhanaHomePage/rss/news.xml", "center")],
    "civ": [("APA News", "https://apanews.net/en/feed/", "center")],
    "sen": [("APA News", "https://apanews.net/en/feed/", "center")],
    "cod": [("Africanews DRC", "https://www.africanews.com/feed/rss", "center")],
    "uga": [("Daily Monitor UG", "https://www.monitor.co.ug/rss.xml", "center")],
    "tza": [("The Citizen TZ", "https://www.thecitizen.co.tz/rss", "center")],
    "moz": [("Club of Mozambique", "https://clubofmozambique.com/feed/", "center")],
    "ago": [("Angop", "https://www.angop.ao/rss/rss.xml", "center")],
    "zwe": [("New Zimbabwe", "https://www.newzimbabwe.com/feed/", "center")],
    "mdg": [("Africanews Madagascar", "https://www.africanews.com/feed/rss", "center")],
    "som": [("Hiiraan Online", "https://www.hiiraan.com/rss.xml", "center")],
    # -------- Americas --------
    "usa": [("Politico", "https://www.politico.com/rss/politicopicks.xml", "lean_left"),
            ("The Hill", "https://thehill.com/rss/syndicator/19110", "center")],
    "can": [("CBC Politics", "https://rss.cbc.ca/lineup/politics.xml", "lean_left")],
    "mex": [("Mexico News Daily", "https://mexiconewsdaily.com/feed/", "center")],
    "gtm": [("Prensa Libre", "https://www.prensalibre.com/feed/", "center")],
    "hnd": [("La Prensa HN", "https://www.laprensa.hn/feed/", "center")],
    "slv": [("El Salvador Perspectives", "https://www.elfaro.net/es/rss", "center")],
    "nic": [("La Prensa NI", "https://www.laprensani.com/feed/", "center")],
    "cri": [("Tico Times", "https://ticotimes.net/feed", "center")],
    "pan": [("Panama Today", "https://www.panamatoday.com/rss.xml", "center")],
    "cub": [("14ymedio", "https://www.14ymedio.com/rss/portada.xml", "lean_right")],
    "dom": [("Dominican Today", "https://dominicantoday.com/feed/", "center")],
    "hti": [("Haitian Times", "https://haitiantimes.com/feed/", "center")],
    "bra": [("The Rio Times", "https://www.riotimesonline.com/feed/", "center")],
    "arg": [("Buenos Aires Times", "https://www.batimes.com.ar/feed", "center")],
    "chl": [("La Tercera", "https://www.latercera.com/feed", "center")],
    "col": [("Colombia Reports", "https://colombiareports.com/feed/", "center")],
    "ven": [("Efecto Cocuyo", "https://efectococuyo.com/feed/", "center")],
    "per": [("Andina News", "https://andina.pe/agencia/rss.aspx", "center")],
    "ecu": [("El Universo", "https://www.eluniverso.com/rss/portada.xml", "center")],
    "bol": [("Los Tiempos", "https://www.lostiempos.com/rss.xml", "center")],
    "ury": [("El Observador UY", "https://www.elobservador.com.uy/rss/portada.xml", "center")],
    "pry": [("ABC Paraguay", "https://www.abc.com.py/rss.xml", "center")],
    # -------- Europe --------
    "gbr": [("The Guardian UK", "https://www.theguardian.com/uk/rss", "lean_left"),
            ("The Independent UK", "https://www.independent.co.uk/rss", "lean_left")],
    "irl": [("RTÉ News", "https://www.rte.ie/rss/news.xml", "center")],
    "fra": [("France 24 English", "https://www.france24.com/en/rss", "lean_left")],
    "deu": [("Deutsche Welle English", "https://rss.dw.com/rdf/rss-en-all", "center")],
    "esp": [("El País English", "https://feeds.elpais.com/mrss-s/pages/ep/site/english.elpais.com/portada", "lean_left")],
    "prt": [("Portugal News", "https://www.theportugalnews.com/rss", "center")],
    "ita": [("ANSA English", "https://www.ansa.it/english/english_rss.xml", "center")],
    "che": [("SwissInfo", "https://www.swissinfo.ch/eng/rss", "center")],
    "aut": [("Der Standard Int.", "https://www.derstandard.at/rss", "lean_left")],
    "bel": [("Brussels Times", "https://www.brusselstimes.com/feed/", "center")],
    "nld": [("Dutch News NL", "https://www.dutchnews.nl/feed/", "center")],
    "lux": [("Luxembourg Times", "https://www.luxtimes.lu/rss.xml", "center")],
    "dnk": [("The Local DK", "https://feeds.thelocal.com/rss/dk", "center")],
    "swe": [("The Local SE", "https://feeds.thelocal.com/rss/se", "center")],
    "nor": [("The Local NO", "https://feeds.thelocal.com/rss/no", "center")],
    "fin": [("YLE News", "https://feeds.yle.fi/uutiset/v1/majorHeadlines/YLE_UUTISET.rss", "center")],
    "isl": [("Iceland Review", "https://www.icelandreview.com/feed/", "center")],
    "pol": [("Notes from Poland", "https://notesfrompoland.com/feed/", "center")],
    "cze": [("Prague Morning", "https://praguemorning.cz/feed/", "center")],
    "svk": [("Slovak Spectator", "https://spectator.sme.sk/rss.asp", "center")],
    "hun": [("Hungary Today", "https://hungarytoday.hu/feed/", "lean_right")],
    "rou": [("Romania Insider", "https://www.romania-insider.com/rss.xml", "center")],
    "bgr": [("Novinite", "https://www.novinite.com/rss.xml", "center")],
    "grc": [("Kathimerini English", "https://www.ekathimerini.com/feed/", "center")],
    "cyp": [("Cyprus Mail", "https://cyprus-mail.com/feed/", "center")],
    "srb": [("N1 Serbia", "https://rs.n1info.com/feed/", "center")],
    "hrv": [("Total Croatia News", "https://total-croatia-news.com/feed/", "center")],
    "svn": [("The Slovenia Times", "https://sloveniatimes.com/feed", "center")],
    "bih": [("N1 BiH", "https://ba.n1info.com/feed/", "center")],
    "mne": [("CDM Montenegro", "https://www.cdm.me/rss/", "center")],
    "alb": [("Exit News AL", "https://exit.al/en/feed/", "center")],
    "mkd": [("Meta.mk", "https://meta.mk/en/feed/", "center")],
    "ukr": [("Kyiv Independent", "https://kyivindependent.com/rss/", "center")],
    "blr": [("Belsat News", "https://belsat.eu/en/feed/", "lean_left")],
    "mda": [("MoldovaMatters", "https://moldovamatters.com/feed/", "center")],
    "rus": [("Moscow Times", "https://www.themoscowtimes.com/rss/news", "lean_left"),
            ("TASS English", "https://tass.com/rss/v2.xml", "right")],
    "est": [("ERR News", "https://news.err.ee/rss", "center")],
    "lva": [("LSM English", "https://eng.lsm.lv/rss/", "center")],
    "ltu": [("LRT English", "https://www.lrt.lt/en/rss", "center")],
    "mlt": [("Times of Malta", "https://timesofmalta.com/rss", "center")],
    "isr": [("Times of Israel", "https://www.timesofisrael.com/feed/", "center")],
    # -------- Middle East / Central Asia --------
    "tur": [("Daily Sabah", "https://www.dailysabah.com/rss/latest", "lean_right"),
            ("Hurriyet Daily News", "https://www.hurriyetdailynews.com/rss", "center")],
    "sau": [("Arab News", "https://www.arabnews.com/rss.xml", "lean_right")],
    "are": [("Khaleej Times", "https://www.khaleejtimes.com/rss/uae", "center")],
    "qat": [("Doha News", "https://dohanews.co/feed/", "center")],
    "kwt": [("Kuwait Times", "https://www.kuwaittimes.com/feed/", "center")],
    "omn": [("Times of Oman", "https://timesofoman.com/rss", "center")],
    "bhr": [("Gulf Daily News", "https://www.gdnonline.com/rss", "center")],
    "jor": [("Jordan Times", "https://jordantimes.com/rss.xml", "center")],
    "lbn": [("L'Orient Today", "https://today.lorientlejour.com/rss.xml", "center")],
    "syr": [("SANA Syria", "https://sana.sy/en/?feed=rss2", "right")],
    "irq": [("Rudaw English", "https://www.rudaw.net/english.rss", "center")],
    "irn": [("Tehran Times", "https://www.tehrantimes.com/rss.xml", "right")],
    "yem": [("Al Masirah English", "https://english.almasirah.net.ye/rss", "lean_left"),
            ("Aden News", "https://adenpr.com/en/feed/", "center")],
    "afg": [("Ariana News", "https://arianaenews.com/feed/", "center")],
    "pak": [("Dawn PK", "https://www.dawn.com/feeds/home", "center")],
    "ind": [("The Hindu", "https://www.thehindu.com/news/national/feeder/default.rss", "lean_left"),
            ("Times of India Top", "https://timesofindia.indiatimes.com/rssfeedstopstories.cms", "center")],
    "bgd": [("The Daily Star BD", "https://www.thedailystar.net/rss.xml", "center")],
    "lka": [("Daily Mirror LK", "https://www.dailymirror.lk/RSS/155", "center")],
    "npl": [("Kathmandu Post", "https://kathmandupost.com/rss", "center")],
    "kaz": [("Astana Times", "https://astanatimes.com/feed/", "center")],
    "uzb": [("Gazeta.uz English", "https://www.gazeta.uz/en/rss/", "center")],
    "kgz": [("24.kg English", "https://24.kg/english/rss/", "center")],
    "tjk": [("Asia-Plus TJ", "https://asiaplustj.info/en/rss.xml", "center")],
    "tkm": [("Turkmenistan Chronicles", "https://en.hronikatm.com/feed/", "center")],
    "aze": [("Trend News AZ", "https://en.trend.az/rss/", "center")],
    "arm": [("ArmenPress", "https://armenpress.am/eng/rss/news/", "center")],
    "geo": [("Agenda.ge", "https://agenda.ge/en/rss", "center")],
    # -------- East / South-East Asia --------
    "chn": [("China Daily World", "https://www.chinadaily.com.cn/rss/world_rss.xml", "right"),
            ("Global Times CN", "https://www.globaltimes.cn/rss/outbrain.xml", "right")],
    "twn": [("Focus Taiwan", "https://focustaiwan.tw/rss/aall.xml", "center")],
    "hkg": [("Hong Kong Free Press", "https://hongkongfp.com/feed/", "lean_left")],
    "jpn": [("NHK World", "https://www3.nhk.or.jp/nhkworld/en/news/all.rss", "center"),
            ("Japan Times", "https://www.japantimes.co.jp/feed/", "center")],
    "kor": [("Yonhap News", "https://en.yna.co.kr/RSS/news.xml", "center"),
            ("Korea Herald", "https://www.koreaherald.com/rss/010000000000.xml", "center")],
    "prk": [("NK News", "https://www.nknews.org/feed/", "center")],
    "mng": [("Montsame English", "https://montsame.mn/en/rss/type/1", "center")],
    "vnm": [("Vietnam Plus", "https://en.vietnamplus.vn/rss/politics.rss", "center")],
    "tha": [("Bangkok Post", "https://www.bangkokpost.com/rss/data/topstories.xml", "center")],
    "khm": [("Khmer Times", "https://www.khmertimeskh.com/feed/", "center")],
    "lao": [("Laotian Times", "https://laotiantimes.com/feed/", "center")],
    "mmr": [("Frontier Myanmar", "https://www.frontiermyanmar.net/en/feed/", "center")],
    "mys": [("The Star MY", "https://www.thestar.com.my/rss/News/Nation", "center")],
    "sgp": [("Channel News Asia SG", "https://www.channelnewsasia.com/rssfeeds/8395986", "center")],
    "idn": [("Jakarta Post", "https://www.thejakartapost.com/rss", "center")],
    "phl": [("PhilStar Headlines", "https://www.philstar.com/rss/headlines", "center")],
    "brn": [("Borneo Bulletin", "https://borneobulletin.com.bn/feed/", "center")],
    # -------- Oceania --------
    "aus": [("ABC News AU", "https://www.abc.net.au/news/feed/45910/rss.xml", "center"),
            ("SMH Politics", "https://www.smh.com.au/rss/politics.xml", "lean_left")],
    "nzl": [("RNZ News", "https://www.rnz.co.nz/rss/national.xml", "center")],
    "fji": [("Fiji Times", "https://www.fijitimes.com/feed/", "center")],
    "png": [("Post-Courier PNG", "https://postcourier.com.pg/feed/", "center")],
}
